### ISSUE TITLE
Aligned option using star

### ISSUE THREAD

**Issue by nttg8100** [ylab-hi/ScanNeo2#21]
In ran on the star 2.7.1a star aligner. The option --chimOutType is not set correctly when I ran it showed me the conflict options.
https://github.com/ylab-hi/ScanNeo2/blob/main/workflow/rules/align.smk#L33C1-L33C34
```
EXITING because of fatal PARAMETERS error: --chimMultimapNmax > 0 (new chimeric detection) presently only works with --chimOutType Junctions
SOLUTION: re-run with --chimOutType Junctions
```
However, the pipeline already sets with ` --chimOutType WithinBAM HardClip`.
Currently, I replace the option as recommended automatically by the software. 
Can you check on the current smk align rule. If it is not set correctly, please update the pipeline.

**Comment by riasc** [comment]
Hello,

is there a reason you are using 2.7.1a and not 2.7.10b (which is the one used by the snakemake star wrapper - should probably update to 2.7.11b)? Or are you not able to use conda? As the authors of STAR are mentioning here: https://github.com/alexdobin/STAR/issues/1288 It's possible to call --chimMultimapNmax with `--chimOutType WithinBAM` in recent versions. We need to have it within the BAM (mainly because of Arriba) and would lose information otherwise.

**Comment by nttg8100** [comment]
I see. Thank you for your clarification. I thought it could be the STAR version issue so I provided above. Currently, I have been used the image from STAR 2.7.1a for calling gene expression, fusion and this alt splicing, exonic introns. I will update later for my pipeline to use a unique version of STAR. Thank you for your support.
