### ISSUE TITLE
Without normal sample

### ISSUE THREAD

**Issue by ilovegreentea** [ylab-hi/ScanNeo2#37]
1. We don't have a normal sample.. Is it okay to run it without a normal sample?
It generate result file well..

2. Is agretopicity indicates binding affinity?
When I googled it says it's the ratio of binding affinity between Normal and tumor.. How did it calculate when we don't have normal..?

Thank you for making great tool

**Comment by riasc** [comment]
Hi there, thanks for using the tool. 

1) Yes, you can also use it without normal samples. Specifying the normal sample in 
https://github.com/ylab-hi/ScanNeo2/blob/adac49d2f96c23a8767a58ce76df3fd536e43618/config/config.yaml#L17
only allows the internal tools to filter out certain variants. For example, GATK (that we use internally for indel calling) allows to provide the normal sample, which can be used to enhance the indel calling (but also works without it) - so its entirely optional.

2) When we calculate the binding affinity, we calculate it for the mutant and the wild type (reference sequence without the mutation). Obviously, we expect that the binding affinity will differ; otherwise, the mutant will not be loaded onto the MHC complex. And the agretopcity is then simply:
```
$$
agretopcity = \frac{mt binding affinity}{wildtype affinity}
$$
```
In other words, this simply describes whether the binding affinities of the mutant and wildtype are equal. If `agretopicty = 1` then they are equal and if `agretopcity < 1` (and close to 0) or `agretopicity > 1` they are unequal.  

The basic idea behind this can be found in this paper:
https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2017.01566/full
The authors showed (Figure 2) that for immunogenic neoantigens, when the binding affinity is similar, the sequence similarity differs (between mutant and wildtype), whereas an increased binding affinity in the mutant (vs. the wildtype) does not show any change difference in the sequence similarity.

So you can use this to filter some detected neoantigens. 

Sorry I saw that the documentation is not available for this. It was initially planned to include this in ScanNeo2 v0.3.x but ended up earlier for internal use - I will change that these days.

Hope that helps. Let me know if you have any questions
